### ISSUE TITLE
Add initial SpaceX API stubs 

### ISSUE THREAD

**Issue by adilanchian** [NITJSR-OSS/My-SpaceX-Console#6]
I think it will be a bit difficult to get started on this project for some if the data is not there!

I would like to propose setting up a service manager to create stubs for calling the SpaceX API. It would be an initial setup so people can add onto to it and learn how to add more endpoints via React :)

**Comment by AdityaPratap006** [comment]
Actually, this is a general practice project to get started with open-source.
I will create a separate branch with name <username_accepted>, and merge the respective PRs there only, not in the master branch. So I guess everyone's free to set up the apis as they want

**Comment by adilanchian** [comment]
I see. Best of luck!

**Comment by AdityaPratap006** [comment]
@adilanchian thanks :)
